Create Airbyte Organization Github Profile
airbytehq/.github pull request #1
Opened 2024-08-22 15:35 UTC by marcosmarxm

Got inspiration from https://github.com/langchain-ai <3
Adds Airbyte org profile README.

2024-08-22 15:54 UTC, perangel commented on profile/README.md
> +- [`Terraform`](https://github.com/langchain-ai/langserve) - declares and have code versioned Airbyte Connectors as code.
Still have some langchain links here

2024-08-22 15:54 UTC, perangel requested changes
Still have a few langchain links

2024-08-23 15:51 UTC, nataliekwong commented on profile/README.md
> +<a href="https://airbytehq.slack.com/" target="_blank">
I thought the community Slack was not airbytehq?

2024-08-23 15:54 UTC, nataliekwong commented on profile/README.md
> +
```suggestion
Airbyte is an open-source data movement infrastructure for building extract and load (EL) data pipelines. It is designed for versatility, scalability, and ease-of-use.
```

2024-08-23 15:55 UTC, nataliekwong commented on profile/README.md
> +- [`Airbyte Cloud`](https://cloud.airbyte.com) - cloud service allows you to focus on moving data while we take care of managing the infrastructure.
```suggestion
- [`Airbyte Cloud`](https://cloud.airbyte.com) - a hosted service that allows you to focus on moving data while we take care of managing the infrastructure
```

2024-08-23 15:59 UTC, nataliekwong commented on profile/README.md
> +- [`Airbyte Enterprise`](https://docs.airbyte.com/enterprise-setup/) - run Airbyte in own your infrastructure with access to Enterprise feature and special support.
```suggestion
- [`Airbyte Enterprise`](https://docs.airbyte.com/enterprise-setup/) -  Run Airbyte in your own infrastructure with added security and team features. 
```

2024-08-23 16:02 UTC, nataliekwong commented on profile/README.md
> +- [`Airbyte Open-Source`](https://docs.airbyte.com/using-airbyte/getting-started/#self-managed-community-oss) - run Airbyte in own infra and have full control over your data.
```suggestion
- [`Airbyte Open-Source`](https://docs.airbyte.com/using-airbyte/getting-started/#self-managed-community-oss) - Deploy on your own infrastructure and start moving data 
```

2024-08-23 16:03 UTC, nataliekwong commented on profile/README.md
> +| [Airbyte Documentation](https://docs.airbyte.com/) | Get started laerning Airbyte concepts and tutorials |
```suggestion
| [Airbyte Documentation](https://docs.airbyte.com/) | Learn how to get started, Airbyte concepts, and our features |
```

2024-08-23 16:03 UTC, nataliekwong commented on profile/README.md
> +| [Company Website](https://airbyte.com) | Airbyte product and company info |
```suggestion
| [Company Website](https://airbyte.com) | Airbyte product and company information |
```

2024-08-23 16:04 UTC, nataliekwong commented on profile/README.md
> +- [`Airbyte`](https://github.com/airbytehq/airbyte) - all Airbyte connectors Python and Java, Airbyte CDK and Airbyte CI tools.
```suggestion
- [`Airbyte`](https://github.com/airbytehq/airbyte) - all Airbyte connectors (Python and Java), Airbyte CDK and Airbyte CI tools.
```

2024-08-23 16:06 UTC, nataliekwong commented on profile/README.md
> +- [`Terraform`](https://github.com/airbytehq/terraform-provider-airbyte) - declares and have code versioned Airbyte Connectors as code.
```suggestion
- [`Terraform`](https://github.com/airbytehq/terraform-provider-airbyte) - declaratively version Airbyte Connectors as code.
```

2024-08-23 16:06 UTC, nataliekwong commented on profile/README.md
> +- [`Helm Charts`](https://artifacthub.io/packages/helm/airbyte/airbyte) - run Airbyte on Kubernetes.
```suggestion
- [`Helm Charts`](https://artifacthub.io/packages/helm/airbyte/airbyte) - run Airbyte at scale on Kubernetes.
```

2024-08-23 16:06 UTC, nataliekwong commented on profile/README.md
> +- [`PyAirbyte`](https://github.com/airbytehq/PyAirbyte) - use Airbyte connectors directly in Python without the Airbyte Platform.
```suggestion
- [`pyAirbyte`](https://github.com/airbytehq/PyAirbyte) - use Airbyte connectors directly in Python without the Airbyte Platform.
```

2024-09-26 23:14 UTC, merged